### ISSUE TITLE
code clean-up

### ISSUE THREAD

**Issue by khollbach** [zrottman/dns_c#15]

**Comment by khollbach** [comment]
saw a button to turn my markdown "checkbox" from the meeting notes into a github issue, so I clicked it!

No pressure to actually tend to this, Zach. :)

**Comment by zrottman** [comment]
This is great, thanks, Kevan. It seems that issues can be linked to specific development branches, which is very cool.

**Comment by zrottman** [comment]
@khollbach Just submited a PR for this issue (#16 ). Would love to review!

**Comment by khollbach** [comment]
Done! Feel free to merge (and close this issue) whenever
